apiVersion: v2
appVersion: 0.1.72
description: A Helm chart for Codefresh gitops runtime
name: gitops-runtime
version: 0.80.0
home: https://github.com/codefresh-io/gitops-runtime-helm
icon: https://avatars1.githubusercontent.com/u/11412079?v=3
keywords:
  - codefresh
  - gitops
maintainers:
  - name: codefresh
    url: https://codefresh-io.github.io/
annotations:
  artifacthub.io/alternativeName: "codefresh-gitops-runtime"
  artifacthub.io/changes: |-
    - kind: changed
      description: 'chore(app-proxy): update cap-app-proxy image tags to 1.3702.0 (#659)'
    - kind: changed
      description: 'test: update platform mock(me) (#656)'
    - kind: changed
      description: 'fix: support failing release if app sync fails (#645)'
    - kind: changed
      description: 'chore(CR-30232): updated oauth2, golang.org/x/net, github.com/cloudflare (#639)'
    - kind: changed
      description: 'chore(app-proxy): update cap-app-proxy image tags to 1.3701.0 (#654)'
    - kind: changed
      description: updated cspd enrichers (#652)
    - kind: changed
      description: 'fix: update leader elector image tag to remove version prefix ''v'' (#651)'
    - kind: changed
      description: 'feat: solve out-of-sync crds in Argo CD v3 (#630)'
    - kind: changed
      description: 'feat: add leader election support to agent and remove from handler (#647)'
    - kind: changed
      description: 'chore: update cap-app-proxy image tags to 1.3694.0 - use proxy env vars in git operations (#646)'
    - kind: changed
      description: quote proxy env vars (#644)
    - kind: changed
      description: 'fix: update workflow submission logic and improve error handling (#625)'
    - kind: changed
      description: 'chore: update cap-app-proxy image tags to 1.3688.0 - fix eventBusName when using jetstream (#636)'
    - kind: changed
      description: 'fix: argo helm bump redis version (#631)'
    - kind: changed
      description: 'feat(app-proxy): add leader election (#621)'
    - kind: changed
      description: 'chore: update cap-app-proxy image tags to 1.3680.0 - fix: return the pushed commit sha (#6560) (#628)'
    - kind: changed
      description: 'chore: Gitops Operator to v0.8.11 to fix 4 issues (#624)'
    - kind: changed
      description: 'fix: GITOPS_OPERATOR_VERSION should be based upon its own tag, and not the chart appVersion (#626)'
    - kind: changed
      description: 'fix: event-reporter should handle applications from a specific argo-cd instance (#618)'
dependencies:
  - name: argo-cd
    repository: https://codefresh-io.github.io/argo-helm
    condition: argo-cd.enabled
    version: 8.0.6-6-cap-v3.0.2-2025-07-06-e9fc72a9
  - name: argo-events
    repository: https://codefresh-io.github.io/argo-helm
    version: 2.4.8-cap-CR-29689
  - name: argo-workflows
    repository: https://codefresh-io.github.io/argo-helm
    version: 0.45.15-v3.6.7-cap-CR-28355
    condition: argo-workflows.enabled
  - name: argo-rollouts
    repository: https://codefresh-io.github.io/argo-helm
    version: 2.37.3-6-v1.7.2-cap-CR-29629
    condition: argo-rollouts.enabled
  - name: sealed-secrets
    repository: https://bitnami-labs.github.io/sealed-secrets/
    version: 2.17.2
  - name: codefresh-tunnel-client
    repository: oci://quay.io/codefresh/charts
    version: 0.1.21
    alias: tunnel-client
    condition: tunnel-client.enabled
  - name: cf-common
    repository: oci://quay.io/codefresh/charts
    version: 0.27.0
